### PR TITLE
Version bump + improvements to svg2pdf

### LINKED ISSUE #46: Wavedrom diagram rendering issues (font, dotted lines)
Hello, I'm trying to use svg2pdf to convert SVG files of Wavedrom diagrams generated by https://github.com/wallento/wavedrompy, but the rendering of text and dotted lines is different from SVG rendering in the browser and seems wrong.
Input SVG:
out
PDF from svg2pdf:
svg2pdf-output

### PR DESCRIPTION
**Pull request by LaurenzV**
This PR:
- Bumps to resvg 0.38. It contains quite a few changes wrt how bboxes are handled, but also the resvg API itself. But these changes are what enable us to easily add filters in the first place.
- Adds support for filters (only a few edge cases are not working correctly yet because they are a bit difficult to handle). The resolution of filters can be changed via a setting (which means it could in theory also be controlled from Typst)
- Improves clip paths with non zero winding rule
- Fixes #46

### CODE REVIEW

**Comment by reknih** [comment]
Thank you for taking this into your own hands! You can also remove Filters from the unsupported features list in the `README` file :)

**Comment by LaurenzV** [comment]
Didn't I already do that? 🤔

**Comment by reknih** [comment]
Oh my bad!

**Comment by reknih** [comment]
Thank you so much!

**Pull request merged**
